### ISSUE TITLE
Security Scheme for BasicAuth should be "basic" instead of "Basic"

### ISSUE THREAD

**Issue by taotao100** [ePages-de/restdocs-api-spec#100]
The Security Scheme generated by [SecuritySchemeGenerator.kt line 56](https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/SecuritySchemeGenerator.kt) for BasicAuth should be "basic" rather than "Basic"
**expected openapi document:**
`components:
  securitySchemes:
    basic:
      type: http
      scheme: basic`
**generated entry:**
`components:
  securitySchemes:
    basic:
      type: http
      scheme: Basic`
The later one does not conform to openapi specification, so that it can not be interpreted by swagger ui & editor correctly, which leads to no BasicAuth header is added in the http-request.

**Comment by ozscheyge** [comment]
Hey @taotao100 ! 

The [OpenAPI 3 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-23) references [RFC7235](https://tools.ietf.org/html/rfc7235#section-5.1), which points to the [Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml).
The entry for "Basic" ([RFC7617](https://tools.ietf.org/html/rfc7617)):
* Defines the scheme name as `Basic`
* But also says "Note that both scheme and parameter names are matched case-
   insensitively."

The OpenAPI 3 spec is not specific on the case-sensitivity, but just lists lower-case examples

**Comment by taotao100** [comment]
It is great, thanks for the commit. it help me in use of the generated openapi documents in Swagger tools, I long for your next release.
