### ISSUE TITLE
Potential Support For Spring Auto REST Docs

### ISSUE THREAD

**Issue by opticyclic** [ePages-de/restdocs-api-spec#102]
Following up on https://github.com/ePages-de/restdocs-api-spec/issues/73 and https://github.com/ScaCap/spring-auto-restdocs/issues/281

for making `restdocs-api-spec` and  `spring-auto-restdocs` work together I saw this interesting project that seems to have done it:

https://github.com/heidelpay/samples-rest-api-documentation/blob/master/src/test/java/com/heidelpay/restdocs/AutoRestDocOpenApiSpecAdapterFactory.java

**Comment by mduesterhoeft** [comment]
Thanks for pointing this out - I will have a look.

**Comment by AriseEVE** [comment]
This approach works but it has problems.  One issue is when you have recursive fields in a model you get an error: "The following parts of the payload were not documented", if any of these fields gets used in a test.
Other issue is auto-restdoc's failOnUndocumentedFields is ignored.
Would be nice if api-spec gets compatible with autodoc.

**Comment by leedoowonc** [comment]
Do you have any plan to integrate with restdocs-api-spec?

**Comment by ozscheyge** [comment]
Ideas and workarounds are outlined in https://github.com/ScaCap/spring-auto-restdocs/issues/281

Afaics, spring-auto-restdocs would need to be adapted first.
Both https://github.com/ScaCap/spring-auto-restdocs/issues/281 and this issue seem to lack interest.

@ePages-de won't invest time, but we are open to review, integrate and release contributions. Till then, I'll close the issue.
