### ISSUE TITLE
Add description annotation

### ISSUE THREAD

**Issue by mali-eg** [ePages-de/restdocs-api-spec#103]
I would like to ask if it possible to add the functionality of reading the fields description from the the models if the fields annotated for example with @Description annotation

**Comment by mduesterhoeft** [comment]
Thanks for the suggestion. But the thing I really like about `spring-restdocs` is its test-driven approach. If you want to go for introspection-driven approaches you might want to look at [springfox](http://springfox.github.io/springfox/)
