### ISSUE TITLE
parameter types

### ISSUE THREAD

**Issue by levippaul** [ePages-de/restdocs-api-spec#110]
The schema type for path and request parameters is being set to string even for numeric values. For instance, for a path parameter that is defined as a Long, the generated document sets the schema type as a string when it should be an integer.

**Comment by mduesterhoeft** [comment]
Sounds reasonable. I think this could be done by extending the PathDescriptor from spring-restdocs.

Would you be in to give it a try.

**Comment by levippaul** [comment]
@mduesterhoeft  yeah, I'd be happy to give it a shot. If there are any pointers that you can share to help me get started, that'd be great!

**Comment by mduesterhoeft** [comment]
Looks like we already have that:

com.epages.restdocs.apispec.ResourceSnippetIntegrationTest#buildFullResourceSnippet

```
.pathParameters(
                            parameterWithName("someId").description("some id"),
                            parameterWithName("otherId").description("otherId id").type(SimpleType.INTEGER)
                    )
```

**Comment by pax95** [comment]
Is there a similar way to specify a ARRAY type. Setting the type to java.util.List generates ->
{
      "attributes" : { },
      "description" : "List of featuring artist if any",
      "ignored" : false,
      "path" : "[].musicInfo.featurings[]",
      "type" : "java.util.List",
      "optional" : true
    } 
in resource.json where it should have been ARRAY

**Comment by ozscheyge** [comment]
Hey @pax95 ,

Spring restdocs tries to infer the type from the example bodies, but you can override this with:
```
fieldWithPath("featurings").type(JsonFieldType.ARRAY).description("List of featuring artist if any")
```

You need to use JsonFieldType types and not the Java types. I hope, this helps!

**Comment by ozscheyge** [comment]
This should be working by now, see
https://github.com/ePages-de/restdocs-api-spec/issues/181#issuecomment-896287474 and the linked example:
https://github.com/ePages-de/restdocs-api-spec/pull/185/files#diff-672ed55d0ceac62de36f9aa7020d71ca27d6bbb03b9c0d7777699d21287191b5R298-R321
