### ISSUE TITLE
Provide usage example for build.gradle.kts

### ISSUE THREAD

**Issue by kubav182** [ePages-de/restdocs-api-spec#112]
Can you please provide example how to configure openapi3 task in build.gradle.kts?

**Comment by axkb** [comment]
@kubav182 , was struggling with the same, but figured this way:
`configure<com.epages.restdocs.apispec.gradle.OpenApi3Extension> {
    setServer("http://$apiHost:$apiPort")
    title = "Your title"
    description = "Your Descr"
    version = "0.1.0"
    format = "json"
    tagDescriptionsPropertiesFile = "src/test/resources/tags.yaml"
}`
hope it helps

**Comment by ozscheyge** [comment]
I added it to the README in https://github.com/ePages-de/restdocs-api-spec/commit/9138472d8d2242643b0544c99cc6d3dee8f52f19
