### ISSUE TITLE
Separator in schema names

### ISSUE THREAD

**Issue by apischan** [ePages-de/restdocs-api-spec#131]
Currently schema names generates with kebab case (e.g. `api-v2-colors-195476272`). But Amazon Gateway do not like such format of schema names. If to try to import such schema it says:
```
Unable to create model for 'api-v1-colors-show-colorId-195476272': Model name must be alphanumeric: api-v1-colors-show-colorId-195476272
```
I see that  #78 already closed and looks merged. When the new release with this fix is expected?

**Comment by apischan** [comment]
I see that this change is already in version 0.9.7.

**Comment by thowimmer** [comment]
Hi @apischan 

I see that its not clear how to use custom schema names. We definitely should improve the documentation in this respect.

I hope that https://github.com/ePages-de/restdocs-api-spec/issues/128#issuecomment-585434241 answers your question.

Let me know if I can help you further in case it's not clear from the comment of the other issue.

**Comment by apischan** [comment]
Hi Thomas

Yes, I've found that one but it doesn't work. Here is the test that I've run.
```
  @Test
  void error() throws Exception {
    this.mockMvc.perform(
        get("/error")
            .requestAttr(RequestDispatcher.ERROR_STATUS_CODE, 500))
        .andExpect(status().isInternalServerError())
        .andDo(document("error",
            resource(
                ResourceSnippetParameters.builder()
                    .responseFields(
                        fieldWithPath("error").description("error"),
                        fieldWithPath("message").description("message"),
                        fieldWithPath("status").description("status"),
                        fieldWithPath("timestamp").description("ts")
                    )
                    .responseSchema(schema("InternalServerError"))
                    .build()
            )
        ));
  }
```

It fails with the following error:
```
Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: 22, column: 16] (through reference chain: com.epages.restdocs.apispec.model.ResourceModel["response"]->com.epages.restdocs.apispec.model.ResponseModel["schema"])
```

But if to comment this line `.responseSchema(schema("InternalServerError"))` then everything is ok.

Whether should I open the new issue for this discussion?

**Comment by apischan** [comment]
@thowimmer sorry for bothering. That was my fault. I've used different versions of plugin and framework. Plugin was 0.9.5 and framework was 0.9.7. Now everything is working.
