### ISSUE TITLE
Response HTTP status is not enclosed in quotation marks in YAML format

### ISSUE THREAD

**Issue by uladzimir-tsyperman** [ePages-de/restdocs-api-spec#139]
HTTP status in `responses` section is not enclosed in quotation marks as it is required by OpenAPI 3 specification: https://swagger.io/specification/#responses-object

Actual:
```yaml
      responses:
        200:
          description: "200"
```
To be:
```yaml
      responses:
        "200":
          description: "200"
```

**Comment by ozscheyge** [comment]
Hey,

thanks for the report! Relevant quote from the spec:

> This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

**Comment by ozscheyge** [comment]
This seems to be an (upstream) serialization issue.

We are correctly passing HTTP status as Strings to the OpenAPI 3 model classes, see: https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3Generator.kt#L300

Seems to be a similar issue to [this upstream issue](https://github.com/swagger-api/swagger-core/issues/3372).
```
        return if (yamlFormats.contains(format)) {
            Yaml.pretty().apply {
                (factory as YAMLFactory).configure(YAMLGenerator.Feature.MINIMIZE_QUOTES, false)
            }.writeValueAsString(openApi)
        } else {
            Json.pretty().writeValueAsString(openApi)
        }
```
in https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/ApiSpecificationWriter.kt might do the trick. But first I'd suggest to bump the `io.swagger.core.v3:swagger-core` version to see if this has been addressed in the meantime.

**Comment by ozscheyge** [comment]
https://github.com/ePages-de/restdocs-api-spec/commit/022cfe40d9df60bb3601a27e6fe1d98e8cc54836 (version bump) seems to have done the trick. 

Before I was getting:

```
      responses:
        200:
          description: "200"
          headers:
            SIGNATURE:
              description: This is some signature
```

After the version bump:
```
      responses:
        "200":
          description: "200"
          headers:
            SIGNATURE:
              description: This is some signature
```

**Comment by ozscheyge** [comment]
Fixed with https://github.com/ePages-de/restdocs-api-spec/releases/tag/0.9.11
