### ISSUE TITLE
Operation identifier should not be the same as example identifier - OpenAPI3

### ISSUE THREAD

**Issue by CalamarBicefalo** [ePages-de/restdocs-api-spec#140]
If you create a couple of tests, for the same endpoint with different content types. restdocs-api-spec will segregate them following the openapi3 spec appropriately, however the ID of the operation is picked ramdomly from the ID of the documents. Conversely, if you set the same ID for both operations, segregation won't happen. 

See output here:
```json
{
  "openapi" : "3.0.1",
  //... 

  "paths" : {
    "/v1/resource/{id}" : {
      "get" : {
         "operationId" : "id-of-the-document-2", //this is the bit that makes no sense to me (can be 1 or 2 in this example)
        //...
        },
        "responses" : {
          "200" : {
            "description" : "200",
            "content" : {
              "application/content-type-1" : {
                "schema" : {
                  "$ref" : "#/components/schemas/schema1"
                },
                "examples" : {
                  "id-of-the-document-1" : { // that ID makes sense there
                    "value" : "whatever"
                  }
                }
              },
              "application/content-type-2" : {
                "schema" : {
                  "$ref" : "#/components/schemas/schema-2"
                },
                "examples" : {
                  "id-of-the-document-2" : { // that ID makes sense there
                    "value" : "another whatever"
                  }
                }
              }
//... 
  },
```

Perhaps it could be reasonable to have a separate operation ID for these scenarios?

**Comment by ozscheyge** [comment]
Hey @CalamarBicefalo ,

the optional parameter would indeed be an option. However, it would shift the current problem to a different area and not solve it.
For this to work, both `document` calls would need to get the same value for "operationId".
If the developer misses this, the gradle plugin needs to pick one, again.

My suggestion is to determine the common prefix of the snippet ID and use this as the operationId.
This builds on the assumption, that if multiple request+response pairs for the same path+HTTP method are documented, they either differ in content-type or are further examples to highlight common request/response bodies.

## Example

Snippet IDs:

```
get-product
get-product_xml
get-product_with_extra_attributes
```

This would be 3 documented requests, resulting in 3 snippet directories. The common prefix is `get-product` which would then be the operationId.

**Comment by CalamarBicefalo** [comment]
ahhh I see what you mean @ozscheyge, you are absolutely right. 

I think your suggestion is ideal! On the one hand it is compliant with the Spring Rest Docs layout - it doesn't introduce openapi3 specific properties, on the other hand it generates a meaningful openapi3 spec, rather than neglecting certain properties as it does at the moment.

I think your solution fixes the issue in a elegant and pragmatic way.

Thank you very much for keeping me in the loop!

**Comment by ozscheyge** [comment]
I will provide a PR

**Comment by CalamarBicefalo** [comment]
Ohhhhh thanks for fixing this @ozscheyge 🎉
