### ISSUE TITLE
Broken link to CartIntegrationTest

### ISSUE THREAD

**Issue by UgmaDevelopment** [ePages-de/restdocs-api-spec#150]
Hello!

I'm new around here, but I stumbled upon this broken link while reading and thought I'd let someone know about it.

![JfUsQLtRZy](https://user-images.githubusercontent.com/19827042/102538177-33383f00-4069-11eb-9a2a-d4ec05918813.gif)

**Comment by ozscheyge** [comment]
Hey @UgmaDevelopment ,

thanks for pointing this out, it's indeed a broken link in the README.

Looks like you included a fix for this with https://github.com/ePages-de/restdocs-api-spec/pull/149
