### ISSUE TITLE
How to generate multiple api-spec?

### ISSUE THREAD

**Issue by YunSeoWon** [ePages-de/restdocs-api-spec#151]
Hello. I have a question regarding api-spec.

I want to manage api-docs by api version. For example, There are two api version (1.0 and 1.1). and I generate two snippets separated version. (generated-snippets and generated-snippets-v1.1)

![image](https://user-images.githubusercontent.com/35602698/103981673-9da25200-51c5-11eb-94cd-43a04773cfc5.png)

and I configured two OpenApi3Extensions
```groovy
configure<OpenApi3Extension> {
    ...
    outputFileNamePrefix = "api-document"
    snippetsDirectory = "build/generated-snippets"
}

configure<OpenApi3Extension> {
    ...
    outputFileNamePrefix = "api-document-v1.1"
    snippetsDirectory = "build/generated-snippets-v1.1"
}
```

but, only one configure<OpenApi3Extension> is valid. (pre-defined configure is invalid) so, openapi3 task result is that:
![image](https://user-images.githubusercontent.com/35602698/103988806-0db6d500-51d2-11eb-8252-af5de082162f.png)

I want to generate api-spec using openapi task like this, 
![스크린샷 2021-01-08 오후 4 53 20](https://user-images.githubusercontent.com/35602698/103988965-48207200-51d2-11eb-9f10-382cfd4a783e.png)

How to generate multiple api-spec?

**Comment by ozscheyge** [comment]
Hey @YunSeoWon ,

this hasn't been a use-case for us, yet. Each gradle plugin generating the target format just provides one task with [one expected configuration](https://github.com/ePages-de/restdocs-api-spec#openapi-301-1) in the build.gradle[.kts] file.

Could this be solved by a branch in your repo and invoking the gradle task twice? The build/output directory should be ignored by git anyway:
```
./gradlew openapi3
git checkout api-document-v1.1
./gradlew openapi3
```

**Comment by YunSeoWon** [comment]
Thank you for answering my question.

I think It is a way solving the problem. But unfortunately, I want to solve the problem while keeping the branch.

**Comment by ozscheyge** [comment]
Okay, I'd say it's a rather special use-case which could be worked around with other tools (e.g. scripting).
The current plugins are designed for a single configuration per target format.

I'd close this issue, but feel free to re-open or provide a PR if you see a solution.
