### ISSUE TITLE
issue with setting type for a path parameter

### ISSUE THREAD

**Issue by alexisparis** [ePages-de/restdocs-api-spec#168]
Hi,
Thanks for your amazing work.
I have an issue regarding the usage of type while generating the openapi v3 spec. It is very close to an already existing issue #110 

I tried the solution mentionned on the previous issue and it works well for query parameter. I tried the same solution on a path parameter but the generated openapi spec still use string for the type :

Here is the configuration that I have used :

```java 
WebTestClient.BodySpec<Driver, ?> driverBodySpec = webClient.get().
            uri("/drivers/{id}", 1).
            accept(MediaType.APPLICATION_JSON).
            header("HEADER", "value").
            exchange().
            expectStatus().isOk().
            expectBody(Driver.class).
            consumeWith(
                    WebTestClientRestDocumentationWrapper.document(DOCUMENT_IDENTIFIER, "get a driver by its id",
                        ResourceDocumentation.resource(
                                ResourceSnippetParameters.
                                        builder().
                                        requestHeaders(
                                                HeaderDocumentation.
                                                        headerWithName("HEADER").
                                                        optional().
                                                        description("optional header when retrieving a driver")
                                        ).
                                        pathParameters(
                                                ResourceDocumentation.
                                                        parameterWithName("id").
                                                        description("the id of a driver").
                                                        type(SimpleType.INTEGER)
                                        ).
                                        responseFields(this.driverFieldDescriptors).
                                        responseSchema(Schema.schema("Driver")).
                                        build()
                        )
                    ));
        driverBodySpec.consumeWith(body -> Assertions.assertEquals(driverJohnDOE, body.getResponseBody()));
```

the generated spec is as follow : 

<img src="https://user-images.githubusercontent.com/462120/113917779-a0561880-97af-11eb-8c0d-bd528cdfe8d5.png" width="480">

I did something similar for a query parameter : 

```java
WebTestClient.BodySpec<List<Driver>, ?> driversBodySpec = webClient.get().
                uri("/drivers?dangerous=true").
                accept(MediaType.APPLICATION_JSON).
                exchange().
                expectStatus().isOk().
                expectBodyList(Driver.class).

                consumeWith(WebTestClientRestDocumentationWrapper.document(DOCUMENT_IDENTIFIER,
                        ResourceDocumentation.resource(
                                ResourceSnippetParameters.
                                        builder().
                                        requestParameters(
                                            // using RequestDocumentation.parameterWithName("dangerous")... does not
                                            // allow to set the type...
                                            ResourceDocumentation.parameterWithName("dangerous").
                                                    optional().
                                                    description("used to filter the drivers according to their dangerous property").
                                                    type(SimpleType.BOOLEAN)
                                        ).
                                        responseFields(
                                            PayloadDocumentation.fieldWithPath("[]").type(JsonFieldType.ARRAY).description("A list of objects")
                                        ).responseFields(
                                            PayloadDocumentation.applyPathPrefix("[]", driverFieldDescriptors)
                                        ).
                                        responseSchema(Schema.schema("Drivers")).
                                        build()
                        ),
```

the generated spec is okay :
<img src="https://user-images.githubusercontent.com/462120/113918569-9aad0280-97b0-11eb-9b08-8731c6d33f1a.png" width="480">

Am I doing it the wrong way? Is there another way to do that?
Also, is there a way to specify the format of a field?

**Comment by ozscheyge** [comment]
Hey @alexisparis ,

thanks for reporting this, it's a bug indeed! Probably a copy-paste programming error:

1. OpenAPI3 query parameters get the type from the parameter descriptor: https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3Generator.kt#L428
2. OA3 path parameter descriptor's type is hard-coded to string: https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3Generator.kt#L411 (prob. copy-pasted from line 419)

The issue isn't present in OpenAPI2 generator:
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20Generator.kt#L419

## OA2, OA3 specifications for reference

In both specs path parameters types are supported, see examples:
* OA2: https://swagger.io/docs/specification/2-0/describing-parameters/
* OA3: https://swagger.io/docs/specification/describing-parameters/#path-parameters

**Comment by alexisparis** [comment]
@ozscheyge Thanks a lot Oliver

**Comment by alexisparis** [comment]
@ozscheyge I tried with the change that you pushed on master and it works. Again, thank you
