### ISSUE TITLE
How to generate the OpenAPI file in both JSON and YAML?

### ISSUE THREAD

**Issue by Jeeppler** [ePages-de/restdocs-api-spec#176]
How to generate the OpenAPI file in both JSON and YAML format?

One can set the format to either `json` or `yaml`. How to output both formats in the same run?

```groovy
openapi3 {
    server = 'https://localhost'
    title = 'MyApp API'
    description = 'MyApp API description'
    tagDescriptionsPropertiesFile = 'src/test/resources/openapi/tags.yaml'
    format = 'json'
}
```

**Comment by ozscheyge** [comment]
Hey @Jeeppler ,

this hasn't been a use-case so far and is not supported. 

This project uses Jackson internally to generate JSON/YAML, so you should be able to work around this with any converter and a custom gradle task.

**Comment by Jeeppler** [comment]
@ozscheyge what would be required to implement the feature in ePages-de/restdoc-api-spec?

**Comment by ozscheyge** [comment]
> @ozscheyge what would be required to implement the feature in ePages-de/restdoc-api-spec?

Here's the common base task for the two Gradle plugins generating OpenAPI 2/3:
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-gradle-plugin/src/main/kotlin/com/epages/restdocs/apispec/gradle/OpenApiBaseTask.kt#L21
Which is then passed down to the OpenAPI3 generator plugin where it's ultimately serialized:
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/ApiSpecificationWriter.kt#L12 (you can work yourself up in the call hierarchy).

It would be nice, if you could realize this in a non-breaking fashion, meaning that `format` supports both a single String value (for single format to write) or a list of String values (for multiple formats).
If you want to do this test-driven, https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-gradle-plugin/src/test/kotlin/com/epages/restdocs/apispec/gradle/ApiSpecTaskTest.kt#L162 would be a good starting point (check usage, add test asserting existence of 2 files, in both formats).
The docs at https://github.com/ePages-de/restdocs-api-spec#common-openapi-configuration should then also be updated.

If you struggle with tests or docs, I could also fix this later. Thanks for the interest!
