### ISSUE TITLE
Upgrade to gradle 7.x

### ISSUE THREAD

**Issue by jyeonjyan** [ePages-de/restdocs-api-spec#196]
Hello.

While smoothly following Getting started
I get an error `Could not find method testCompile() for arguments` and make a request.

In a way, this is a very simple error.

However, since it is an open source project, 
I respectfully request it because I thought it would be good to always keep the latest version of README.

As of Gradle 7, the testCompile method has been removed.
<img width="700" alt="Screen Shot 2022-01-28 at 1 46 37 AM" src="https://user-images.githubusercontent.com/67095821/151405961-b902d646-3f8a-4b80-945e-789f173d5c56.png">

It would be appreciated if you correct the `2.2/dependencies/testCompile()` configuration with `testImplementation()`.
```groovy
testImplementation('com.epages:restdocs-api-spec-mockmvc:0.15.1') //2.2 | works with Gradle 7 version
```

Thank you for developing a great product 🙂

**Comment by ozscheyge** [comment]
Hey @jyeonjyan ,

that's true and thanks for pointing it out! Looks like, you managed anyway. :)

We aren't explicit on the gradle version we use for the example, we just assumed the same as the [gradle wrapper included in this project](https://github.com/ePages-de/restdocs-api-spec/blob/master/gradle/wrapper/gradle-wrapper.properties#L3), which is basically a year old ( https://gradle.org/releases/ ), but still works fine.

The solution space:

* Update gradle wrapper to 7.x, update the example
* Be explicit about the gradle version in the example
* Maybe, provide examples for each gradle version

**Comment by ozscheyge** [comment]
This is done
