### ISSUE TITLE
Restdocs API Spec Gradle Plugin not generated for Tag 1.16.1

### ISSUE THREAD

**Issue by tadlakha9** [ePages-de/restdocs-api-spec#203]
Hello @ooz , Tag 1.16.1 is not generated well, gradle plugin was not generated https://mvnrepository.com/artifact/com.epages/restdocs-api-spec-gradle-plugin?repo=gradle-plugins, 
as we got some exception in the pipeline (https://app.travis-ci.com/github/ePages-de/restdocs-api-spec/builds/250052030#L2269-L2273)

![image](https://user-images.githubusercontent.com/51110539/166216431-7abe6592-b0b8-4027-b570-764bbcea213b.png)

Could you do the needful, so that we can proceed with this new tag

**Comment by ozscheyge** [comment]
I feared that, since I had a typo in the tag name. I'll try again, sorry for the inconvenience!
