### ISSUE TITLE
v0.16.3 release artifacts seems not uploaded in the respository

### ISSUE THREAD

**Issue by Kieun** [ePages-de/restdocs-api-spec#221]
Gradle plugin (v0.16.3) is upload. But, the release artifacts cannot be retrieved from the maven repository.

**Comment by ozscheyge** [comment]
It usually takes a bit till it shows up on Maven Central/sonatype:
https://search.maven.org/artifact/com.epages/restdocs-api-spec/0.16.3/jar

**Comment by Kieun** [comment]
While testing with v0.16.3, it seems that classes in the restdocs-api-spec are not visible to the application.
By adding restdocs-api-spec in the depednecy, the application can access the class.
But, I'm thinking that this is not intended by design and it's breaking changes.

**Comment by Kieun** [comment]
Close the issue since the artifacts are now accessible from the maven repository.
