### ISSUE TITLE
Generated examples are saved as string instead of JSON objects

### ISSUE THREAD

**Issue by Sirze01** [ePages-de/restdocs-api-spec#230]
The generated OpenAPI specification (using v3.0 here) saves examples as strings, instead of as JSON objects, causing them to be incorrectly parsed by some implementations (fails with Redoc).  

``` JSON
"401" : {
            "description" : "401",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/error-response"
                },
                "examples" : {
                  "AUTH/CheckToken/should fail when access token is invalid" : {
                    "value" : "{\"errors\":[{\"message\":\"An error occurred while attempting to decode the Jwt: Invalid JWT serialization: Missing dot delimiter(s)\"}]}" // Object saved as String
                  }
                }
              }
            }
          },
```

**Comment by ooz** [comment]
Same issue as https://github.com/ePages-de/restdocs-api-spec/issues/111 https://github.com/ePages-de/restdocs-api-spec/issues/109
For OpenAPI3+yaml a workaround is posted here: https://github.com/ePages-de/restdocs-api-spec/issues/109#issuecomment-736012775

**Comment by Sirze01** [comment]
Sorry for creating a duplicate, I couldn't take the meaning from the titles of the other two issues.
I had already considered such a workaround and wanted to leave the issue here. Thanks @ooz ! Should we mark the issue as duplicate and close it?
