### ISSUE TITLE
Keep supporting Spring Boot 2.7.x

### ISSUE THREAD

**Issue by Kieun** [ePages-de/restdocs-api-spec#248]
Due to some limitations, we are still leveraging the Spring Boot 2.7.x. Is there any plan to keep supporting Spring Boot 2.7.x?
FYI, the 2.7.x version will be supported until the mid of 2025.

https://spring.io/projects/spring-boot#support

**Comment by Kieun** [comment]
I've done some jobs to keep supporting the Spring Boot 2.7.x and maintain 0.16.x train.
I've create a new branch `maintenance/0.16` on my forked repo to keep integrating new features and bug fixes from the master train.
As I try to create pull-request to the original repo, since I have no write permission, I cannot create a new branch in this repo.

@ozscheyge @ooz Could you create a branch for this?

FYI, you can refer the jobs:
- https://github.com/Kieun/restdocs-api-spec/tree/maintenance/0.16

**Comment by wodrobina** [comment]
@Kieun here you go. I've prepared branch for you https://github.com/ePages-de/restdocs-api-spec/tree/maintenance/0.16

**Comment by Kieun** [comment]
@wodrobina I opened the #261. Please check it and let me know if anything is wrong.

**Comment by izeye** [comment]
This seems to have been done via https://github.com/ePages-de/restdocs-api-spec/pull/261.

**Comment by izeye** [comment]
[0.16.5](https://github.com/ePages-de/restdocs-api-spec/releases/tag/0.16.5) that contains this change has been release-tagged on Mar 4, but it doesn't seem to have been published to the Maven central repository.

@wodrobina Do you have a plan to publish it?

See https://central.sonatype.com/artifact/com.epages/restdocs-api-spec-mockmvc/versions
