### ISSUE TITLE
Plugin not found when using the new Plugin DSL notation in build.gradle

### ISSUE THREAD

**Issue by thugcee** [ePages-de/restdocs-api-spec#36]
Plugin configuration:

*settings.gradle*:
```
pluginManagement {
  repositories {
      gradlePluginPortal()
      maven { url = uri("https://jitpack.io") }
  }
}
```
*build.gradle*:
```
plugins {
    [...]
    id 'com.epages.restdocs-openapi' version '0.2.1'
}
```

Generated urls are different for classic configuration using `buildscript` and a new one with `plugins`:
```
https://jitpack.io/com/github/epages-de/restdocs-openapi/restdocs-openapi-gradle-plugin/0.2.1/restdocs-openapi-gradle-plugin-0.2.1.pom
https://jitpack.io/com/epages/restdocs-openapi/com.epages.restdocs-openapi.gradle.plugin/0.2.1/com.epages.restdocs-openapi.gradle.plugin-0.2.1.pom
```
The first one is from `buildscript` and works.

**Comment by mduesterhoeft** [comment]
Currently we are not publishing the plugin to the gradle plugin portal, but only to jitpack. The jitpack convention for groupname and artifact id is a little odd. 

You could try to add a custom `resolutionStrategy` like explained here - https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_resolution_rules

**Comment by thugcee** [comment]
hmm... Then maybe I should create an issue in jitpack's tracker.

Some info which can be useful for you: 
https://vkuzel.com/publishing-gradle-plugin-plugins-dsl-on-jitpack-io (Publishing Gradle plugin (plugins DSL) on JitPack.io)
And it works for this plugin https://github.com/vkuzel/Quantum-Leap-Gradle-Plugin

**Comment by mduesterhoeft** [comment]
Ok than it might be also enough to change the plugin id. I will try this out.

**Comment by chadlwilson** [comment]
Hello @klieber - with the [removal of Jitpack](https://github.com/ePages-de/restdocs-api-spec/commit/f8d8dce54795cd210af265af94c06010fa54a515); does that make it easier to get this plugin published to plugins.gradle.org? Would be great to get rid of need for `buildscript` blocks. This is the only plugin of 11 that we use that requires use of `buildscript`.
