### ISSUE TITLE
Option to exclude examples

### ISSUE THREAD

**Issue by lomeshpatel** [ePages-de/restdocs-api-spec#58]
Gradle plugin generates following

```
openapi: 3.0.1
info:
  title: Testing ReDoc
  version: 1.0.0
servers:
- url: http://localhost
paths:
  /public/v1/integrations/recommended:
    get:
      tags:
      - public
      summary: Get Recommended Connectors - Public
      description: Returns list of connectors that are currently not installed, but
        are recommended based on the CSM and third party data.
      operationId: public-recommended-integrations
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/public-v1-integrations-recommended47899855'
              examples:
                public-recommended-integrations:
                  value: '[{"providerId":"2d889796-8174-4c5d-84fb-50c8a87942fa","providerName":"slack","confidenceScore":0.97}]'
components:
  schemas:
    public-v1-integrations-recommended47899855:
      type: array
      items:
        type: object
        properties:
          confidenceScore:
            type: number
            description: ""
          providerId:
            type: string
            description: ""
          providerName:
            type: string
            description: ""
```

This causes ReDoc to NOT format the sample response.
![image](https://user-images.githubusercontent.com/453290/49598494-c43d9100-f94c-11e8-8fe3-7649b0ed9b31.png)

When `examples` section is removed, it is formatted correctly and "Expand All" and "Collapse All" also work.

```
openapi: 3.0.1
info:
  title: Testing ReDoc
  version: 1.0.0
servers:
- url: http://localhost
paths:
  /public/v1/integrations/recommended:
    get:
      tags:
      - public
      summary: Get Recommended Connectors - Public
      description: Returns list of connectors that are currently not installed, but
        are recommended based on the CSM and third party data.
      operationId: public-recommended-integrations
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/public-v1-integrations-recommended47899855'
#              examples:
#                public-recommended-integrations:
#                  value: '[{"providerId":"2d889796-8174-4c5d-84fb-50c8a87942fa","providerName":"slack","confidenceScore":0.97}]'
components:
  schemas:
    public-v1-integrations-recommended47899855:
      type: array
      items:
        type: object
        properties:
          confidenceScore:
            type: number
            description: ""
          providerId:
            type: string
            description: ""
          providerName:
            type: string
            description: ""
```
![image](https://user-images.githubusercontent.com/453290/49598875-97d64480-f94d-11e8-8c98-3b2ef12a4b63.png)

Further more, if the `schema` is updated with `example`, the sample data is populated.

```
openapi: 3.0.1
info:
  title: Testing ReDoc
  version: 1.0.0
servers:
- url: http://localhost
paths:
  /public/v1/integrations/recommended:
    get:
      tags:
      - public
      summary: Get Recommended Connectors - Public
      description: Returns list of connectors that are currently not installed, but
        are recommended based on the CSM and third party data.
      operationId: public-recommended-integrations
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/public-v1-integrations-recommended47899855'
#              examples:
#                public-recommended-integrations:
#                  value: '[{"providerId":"2d889796-8174-4c5d-84fb-50c8a87942fa","providerName":"slack","confidenceScore":0.97}]'
components:
  schemas:
    public-v1-integrations-recommended47899855:
      type: array
      items:
        type: object
        properties:
          confidenceScore:
            type: number
            description: ""
            example: 0.97
          providerId:
            type: string
            description: ""
            example: 2d889796-8174-4c5d-84fb-50c8a87942fa
          providerName:
            type: string
            description: ""
            example: slack
```
![image](https://user-images.githubusercontent.com/453290/49598727-4037d900-f94d-11e8-83dd-277e4b02eec7.png)

Please let me know if I'm missing something here. Or if there's an easy way to achieve the same formatting.

If not, it would be great if this was the default behavior, or at least an option to exclude `examples` section, so ReDoc will format the sample data correctly.

**Comment by mduesterhoeft** [comment]
I am not sure I get your point here. Is it just that you are worried of the json response not being pretty printed?

Of course our extension could prettify the requests and responses but I think I would rather leave this to `spring-restdocs` - it already provides features that can help you there - please see - https://docs.spring.io/spring-restdocs/docs/2.0.2.RELEASE/reference/html5/#customizing-requests-and-responses-preprocessors-pretty-print

Is that helping?

**Comment by lomeshpatel** [comment]
Apologies, if the question was not very clear.

I'm familiar with "pretty-print" preprocessor. What I'm referring to here is ReDoc's ability to automatically prettify the requests and responses.

ReDoc can prettify JSON payloads based on the JSON Schema provided in OpenAPI spec. But, it looks like this prettification doesn't work if `examples` section is present (please see the commented out part of the OpenAPI spec above).

So, my request is an option to exclude `examples` section from the generated OpenAPI spec.

Also, values from the provided example can be applied to `example` field in the schema definition for each of the payload properties, so that ReDoc can use them (Please see the last OpenAPI spec and screenshot above).

Please let me know if you have any further questions.

**Comment by mduesterhoeft** [comment]
Redoc generates the example from the schema if it does not find an example. But isn't a real example much better that a generated one? 

Sorry, but I have my doubts that this feature is useful. You could always post process the generated api spec on your own...

**Comment by Somebody25** [comment]
@lomeshpatel try to remove the single quotes in the beginning and the end of the example payload. I have a similar problem with the generated example when I import it into Postman. When I remove the quotes the example is correctly used by Postman, when I leave them Postman reads it like in your example. By specification it's valid to omit the quotes: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#example-object-example
