### ISSUE TITLE
How to export Rest as a one open api 3.0 file with all informations?

### ISSUE THREAD

**Issue by mertowski** [ePages-de/restdocs-api-spec#60]
Hello all,

do your software generates rest service doc automatically, because i checked your code and i seen that your rest docs written manually regarding your service; so if I change my rest service, the rest docs are not going to generate automatically. Is there anyway to get my rest service automatically for open api 3.0.

[Why I can't get my final result like this example in swagger 2.0?](https://petstore.swagger.io/v2/swagger.json )

**Comment by mertowski** [comment]
I updated my question. @mduesterhoeft

**Comment by mduesterhoeft** [comment]
@mertowski  sorry I still do not understand.

> so if I change my rest service, the rest docs are not going to generate automatically.

What do you mean by that?

**Comment by mertowski** [comment]
I mean, you dont have a docs generator for your rest servies. You created the rest docs  manually by restdocs-api-spec/samples/restdocs-api-spec-sample/src/test/java/com/epages/restdocs/apispec/sample/**CartIntegrationTest.java**

**Comment by mduesterhoeft** [comment]
This is correct and this is how `spring-restdocs` work. In this case I have the feeling that `spring-restdocs` and `restdocs-api-spec` is just not what you are looking for...
