### ISSUE TITLE
Aggregate parameters & descriptions from multiple snippets

### ISSUE THREAD

**Issue by cnsgithub** [ePages-de/restdocs-api-spec#63]
If the request path and method are equal, parameters used during different requests in tests should be aggregated into the same endpoint description.
Example:
````
Testcase1: GET /foo?param=1
Testcase2: GET /foo?otherParam="test"
````
should result in both params being documented. 

Currently this is not the case, the ApiGenerator extracts the parameters from the first ``resource.json`` it finds. See [OpenApi3Generator.kt](https://github.com/ePages-de/restdocs-api-spec/blob/aa604ed814f9a9c994a50521ad2014c9cbea0d9f/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3Generator.kt#L219)

Aggregating the parameters would be useful, if valid requests to an endpoint as well es the error responses should be documented in the OpenAPI specification. In this case, making a request with missing parameters would make sense, to test and document the expected error code from the service.

**Comment by mduesterhoeft** [comment]
Nice catch - I agree - we should aggregate the different params here.

A contribution to fix this issue would be highly appreciated

**Comment by cnsgithub** [comment]
PR: #69
