### ISSUE TITLE
Add top level tags in generated open api spec

### ISSUE THREAD

**Issue by pgcarter** [ePages-de/restdocs-api-spec#65]
I would like the ability to configure top level tags through the plugin. As per example below tags can be configured with a name and description. When I import the spec into swagger ui I get my operations grouped by these tags.

```{
  "swagger": "2.0",
  "info": {
    "description": "The API to for all things cart.",
    "version": "1.0.0",
    "title": "Cart API"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "Cart Services",
      "description": "All things related to cart."
    }
  ],
  "schemes": [
    "https"
  ],
```

**Comment by mduesterhoeft** [comment]
Thanks for suggesting this feature. This surely makes sense. We could handle this the same way we handle scope descriptions. This is currently possible by specifying a reference file. 

@pgcarter why don't you it a try and submit a PR?
