### ISSUE TITLE
Add titleDescription as an optional plugin attribute 

### ISSUE THREAD

**Issue by pgcarter** [ePages-de/restdocs-api-spec#66]
I would like to add a title description as an optional attribute to the plugin so that I can set the description of the API in the [Info object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#info-object)

e.g.
```openapi { //6
    host = 'localhost:8080'
    basePath = '/api'
    title = 'My API'
    titleDescription = 'My API description'
    version = '1.0.0'
    format = 'json'
}

openapi3 {
	server = 'https://localhost:8080'
	title = 'My API'
	titleDescription = 'My API description'
	version = '0.1.0'
	format = 'yaml'
}
```

**Comment by mduesterhoeft** [comment]
Sounds reasonable - I would suggest to call the field just `description`
