### ISSUE TITLE
Help with WebTestClient and spring-auto-restdocs

### ISSUE THREAD

**Issue by samyem-safe2net** [ePages-de/restdocs-api-spec#73]
It appears that webflux tests with WebTestClient is not supported. Is this something in radar and can a sample code be provided on top of the current adapters for rest assured and springmvc test?

**Comment by mduesterhoeft** [comment]
restdocs-api-spec is basically just providing another snippet to spring-restdocs. So this works out of the box for everything spring-restdocs supports. 

We are just providing additional convenience for MockMvc and RestAssured if you have existing tests you want to migrate to `restdocs-api-spec`.

I added another sample for `WebTestClient` so it becomes more clear - [samples/restdocs-api-spec-sample-web-test-client](https://github.com/ePages-de/restdocs-api-spec/tree/master/samples/restdocs-api-spec-sample-web-test-client).

**Comment by samyem-safe2net** [comment]
Thanks for the sample. I think my issue seems to be trying to use it with https://github.com/ScaCap/spring-auto-restdocs rather than the WebTestClient itself.  With it, the setup is generally to call commonDocumentation on consumeWith which is defined as:

```
    protected <T extends ExchangeResult> Consumer<T> commonDocumentation(Snippet... snippets) {
        return document("{class-name}/{method-name}", preprocessRequest(), commonResponsePreprocessor(), snippets);
    }

    protected OperationResponsePreprocessor commonResponsePreprocessor() {
        return preprocessResponse(replaceBinaryContent(), limitJsonArrayLength(objectMapper), prettyPrint());
    }    

```

So trying to understand how I can inject the ResourceDocumentation.resource with this setup.

**Comment by mduesterhoeft** [comment]
`spring-auto-restdocs` does not work with `restdocs-api-spec` - see here for an explanation https://github.com/ScaCap/spring-auto-restdocs/issues/281#issuecomment-446366928
