### ISSUE TITLE
Unrecognized field "X"

### ISSUE THREAD

**Issue by JVecsei** [ePages-de/restdocs-api-spec#82]
In my CustomFieldDescriptor I also have an additional attribute for the internal restdocs document.

Sadly the object mapper does not like that 

`Unable to parse snippet file: /.../target/generated-snippets/.../resource.json: Unrecognized field "X"`

Would be nice if unknown fields could be ignored here 👍

**Comment by mduesterhoeft** [comment]
That sounds like a bug - is this error coming from the gradle plugin? 
Sounds like a great first contribution - we just need to configure the ObjectMapper accordingly to allow unknown fields:

https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-gradle-plugin/src/main/kotlin/com/epages/restdocs/apispec/gradle/PostmanTask.kt#L27

**Comment by SanderSmee** [comment]
I'm using the `MockMvcRestDocumentationWrapper` to wrap my current spring-restdoc test, as a start to generating an OpenAPI specification. 
I'm using the `org.springframework.restdocs.payload.FieldDescriptor` with additional attributes for the restdocs. 

This fails the generation of an OpenAPI spec:

```
Unable to parse snippet file: ~/Projects/app/target/generated-snippets/get-endpoint/resource.json: Unrecognized field "format" (class com.epages.restdocs.apispec.model.Attributes), not marked as ignorable (one known property: "validationConstraints"])
[ERROR]  at [Source: (File); line: 32, column: 8] (through reference chain: com.epages.restdocs.apispec.model.ResourceModel["response"]->com.epages.restdocs.apispec.model.ResponseModel["responseFields"]->java.util.ArrayList[0]->com.epages.restdocs.apispec.model.FieldDescriptor["attributes"]->com.epages.restdocs.apispec.model.Attributes["format"])
```

**Comment by mduesterhoeft** [comment]
@SanderSmee same issue - I am going to fix this asap.

**Comment by mduesterhoeft** [comment]
I had a look - the object mapper instances used in the gradle plugin are ignoring unkown fields. Are you guys using the maven plugin? This resides here https://github.com/BerkleyTechnologyServices/restdocs-spec 

It seems to not ignore unkown properties.

**Comment by SanderSmee** [comment]
Yes indeed I am.
I had not noticed that it issue originated there.

**Comment by mduesterhoeft** [comment]
Please see https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/31

**Comment by JVecsei** [comment]
Thank you for taking care of this issue!
