### ISSUE TITLE
Add contact support?

### ISSUE THREAD

**Issue by lzhoucs** [ePages-de/restdocs-api-spec#88]
This is minor functionaility, but I wonder if we could add support for [contactObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#contactObject)?

**Comment by mduesterhoeft** [comment]
It is minor - but still - why not?

**Comment by mpbalmeida** [comment]
I've created a PR #208 to enable this feature, @mduesterhoeft can you review it?
