### ISSUE TITLE
Attributes for HeaderDescriptor and ParameterDescriptor are ignored.

### ISSUE THREAD

**Issue by navagator-blue** [ePages-de/restdocs-api-spec#95]
The restdocs type `ParameterDescriptor` contains an inherited map of attributes that may be used to define constraints.
But this `attributes` map is ignored when `ParameterDescriptorWithType` is created in `ResourceSnippetParameters.kt:128`.
Due to this problem constraints are ignored for path variables.

Edit @ozscheyge :
Same applies to `HeaderDescriptorWithType`

**Comment by mduesterhoeft** [comment]
Thanks for reporting this issue. Do you want to try to provide a PR. Looks like a good candidate for a fist contribution.

**Comment by navagator-blue** [comment]
Sure, I'll give it a shot

**Comment by iwaltgen** [comment]
@mduesterhoeft Can I try this PR? 🤔
