### ISSUE TITLE
Add support for Postman Variables.

### ISSUE THREAD

**Issue by devtribe** [ePages-de/restdocs-api-spec#98]
It would be nice if we can also use Variables as the baseUrl for generated Postman collections, to use different environments easily. 

See https://learning.getpostman.com/docs/postman/environments_and_globals/variables/ for documentation.

With the current version of restdocs-api-spec i get an Exception  `java.net.URISyntaxException: Illegal character in authority at index 8: https://{{url}}:8080`

**Comment by mduesterhoeft** [comment]
Thanks for reporting this issue. This indeed sounds like it should be supported. 

Would you be in to give it a try?

I think this would be the place that we need to look at: https://github.com/ePages-de/restdocs-api-spec/blob/672460d992dedd5f9a0343a2fc1fff4c070fd915/restdocs-api-spec-postman-generator/src/main/kotlin/com/epages/restdocs/apispec/postman/PostmanCollectionGenerator.kt#L84
